=== Alvaro95pa/TFG_Alvaro_Pavon_URJC/roleplay_framework/lib/mapper/map.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema targetNamespace="http://www.w3schools.com"
    elementFormDefault="qualified"
    xmlns="http://www.w3schools.com map.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="map">
  <xs:complexType>
  	<xs:sequence>
  		<xs:element name="node" minOccurs="1" maxOccurs="unbounded">
		  <xs:complexType>
		  	<xs:sequence>
			    <xs:element name="point" minOccurs="1" maxOccurs="1">
			    	<xs:complexType>
			    		<xs:sequence>
			    			<xs:element name="x" type="xs:integer"/>
			    			<xs:element name="y" type="xs:integer"/>
			    		</xs:sequence>
			    	</xs:complexType>
			    </xs:element>
			    <xs:element name="dungeon" minOccurs="1" maxOccurs="1">
			    	<xs:complexType>
			    		<xs:sequence>
			    			<xs:element name="name" type="xs:string"/>
			    			<xs:element name="description" type="xs:string"/>
			    		</xs:sequence>
			    	</xs:complexType>
			    </xs:element>
			    <xs:element name="adjacent">
			    	<xs:complexType>
			    		<xs:sequence>
			    			<xs:element name="point" minOccurs="0">
						    	<xs:complexType>
						    		<xs:sequence>
						    			<xs:element name="x" type="xs:integer"/>
						    			<xs:element name="y" type="xs:integer"/>
						    		</xs:sequence>
						    	</xs:complexType>
						    </xs:element>
			    		</xs:sequence>
			    	</xs:complexType>
			    </xs:element>
		    </xs:sequence>
		  </xs:complexType>
  		</xs:element>
  	</xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== Alvaro95pa/TFG_Alvaro_Pavon_URJC/game/egyptianScape/app/assets/config/pyramidMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.w3schools.com/map.xsd"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.w3schools.com/map.xsd ../config/map.xsd">
	<node>
		<point>
			<x>0</x>
			<y>-10</y>
			<z>-1</z>
		</point>
		<dungeon>
			<name>Altar de rituales</name>
			<description>La estancia está escasamente iluminada por antorchas. Hay grandes indicios de que en la estancia se realizaban extraños rituales.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>0</x>
				<y>-10</y>
				<z>0</z>
			</point>
		</adjacent>
	</node>
	<node>
		<point>
			<x>0</x>
			<y>-10</y>
			<z>0</z>
		</point>
		<dungeon>
			<name>Antesala del altar</name>
			<description>Una sala pequeña con cuatro entradas. Una de ellas está bloqueada por escombros.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>0</x>
				<y>-10</y>
				<z>-1</z>
			</point>
			<point>
				<x>-1</x>
				<y>-10</y>
				<z>0</z>
			</point>
			<point>
				<x>1</x>
				<y>-10</y>
				<z>0</z>
			</point>
		</adjacent>
	</node>
	<node>
		<point>
			<x>-1</x>
			<y>-10</y>
			<z>0</z>
		</point>
		<dungeon>
			<name>Pasadizo estrecho</name>
			<description>Aunque cabe una persona, este pasadizo es muy estrecho. Probablemente se trate de un pasadizo secreto que terminó quedando abierto.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>0</x>
				<y>-10</y>
				<z>0</z>
			</point>
			<point>
				<x>-1</x>
				<y>-10</y>
				<z>1</z>
			</point>
		</adjacent>
	</node>
	<node>
		<point>
			<x>1</x>
			<y>-10</y>
			<z>0</z>
		</point>
		<dungeon>
			<name>Pasadizo estrecho</name>
			<description>Aunque cabe una persona, este pasadizo es muy estrecho. El pasadizo termina en un muro de piedra. No hay salida por el otro lado.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>0</x>
				<y>-10</y>
				<z>0</z>
			</point>
		</adjacent>
	</node>
	<node>
		<point>
			<x>-1</x>
			<y>-10</y>
			<z>1</z>
		</point>
		<dungeon>
			<name>Dormitorio común</name>
			<description>Una estancia grande con viejas camas de madera podrida. En esta habitación dormían varias personas.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>0</x>
				<y>-10</y>
				<z>1</z>
			</point>
			<point>
				<x>-2</x>
				<y>-10</y>
				<z>1</z>
			</point>
		</adjacent>
	</node>
	<node>
		<point>
			<x>-2</x>
			<y>-10</y>
			<z>1</z>
		</point>
		<dungeon>
			<name>Zona de baños</name>
			<description>Estancia enorme repleta de piscinas de agua estancada. Hay canales y cañerías que en su día hacían fluir el agua.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>-1</x>
				<y>-10</y>
				<z>1</z>
			</point>
		</adjacent>
	</node>
	<node>
		<point>
			<x>0</x>
			<y>-10</y>
			<z>1</z>
		</point>
		<dungeon>
			<name>Comedor</name>
			<description>Los restos podridos de mesas y sillas de madera, así como de utensilios como cuencos demuestran que en otro tiempo esta sala fue el comedor.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>-1</x>
				<y>-10</y>
				<z>1</z>
			</point>
			<point>
				<x>1</x>
				<y>-10</y>
				<z>1</z>
			</point>
		</adjacent>
	</node>
	<node>
		<point>
			<x>1</x>
			<y>-10</y>
			<z>1</z>
		</point>
		<dungeon>
			<name>Dormitorio común</name>
			<description>La amplitud de la sala y los restos de numerosas camas sugieren que aquí dormía un gran número de personas.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>0</x>
				<y>-10</y>
				<z>1</z>
			</point>
			<point>
				<x>1</x>
				<y>-10</y>
				<z>2</z>
			</point>
		</adjacent>
	</node>
	<node>
		<point>
			<x>2</x>
			<y>-10</y>
			<z>1</z>
		</point>
		<dungeon>
			<name>Zona de baños</name>
			<description>Casi todas las piscinas están vacías, a excepción de una. Tal vez esconda algo.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>2</x>
				<y>-10</y>
				<z>2</z>
			</point>
		</adjacent>
	</node>
	<node>
		<point>
			<x>-1</x>
			<y>-10</y>
			<z>2</z>
		</point>
		<dungeon>
			<name>Estancia en ruinas</name>
			<description>Esta sala se encuentra derruída en su mayoría. Hay un agujero con una escalera de mano de madera que parece llevar a una estancia inferior.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>-1</x>
				<y>-10</y>
				<z>1</z>
			</point>
		</adjacent>
	</node>
	<node>
		<point>
			<x>1</x>
			<y>-10</y>
			<z>2</z>
		</point>
		<dungeon>
			<name>Armería</name>
			<description>La sala está repleta de viejas espadas, lanzas y restos de armaduras. Parece la armería de la guardia de este lugar.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>1</x>
				<y>-10</y>
				<z>1</z>
			</point>
			<point>
				<x>2</x>
				<y>-10</y>
				<z>2</z>
			</point>
			<point>
				<x>1</x>
				<y>-10</y>
				<z>3</z>
			</point>
		</adjacent>
	</node>
	<node>
		<point>
			<x>2</x>
			<y>-10</y>
			<z>2</z>
		</point>
		<dungeon>
			<name>Estancia carbonizada</name>
			<description>Las paredes están negras y el suelo está repleto de ceniza. Aquí tuvo lugar un horrible accidente.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>1</x>
				<y>-10</y>
				<z>2</z>
			</point>
			<point>
				<x>2</x>
				<y>-10</y>
				<z>1</z>
			</point>
		</adjacent>
	</node>
	<node>
		<point>
			<x>0</x>
			<y>-10</y>
			<z>3</z>
		</point>
		<dungeon>
			<name>Entrada principal</name>
			<description>La sala tiene una puerta enorme. Se puede sentir una pequeña brisa entrando por las rendijas del portón. Puede que al otro lado se encuentre la salida.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>0</x>
				<y>-10</y>
				<z>4</z>
			</point>
			<point>
				<x>1</x>
				<y>-10</y>
				<z>3</z>
			</point>
		</adjacent>
	</node>
	<node>
		<point>
			<x>1</x>
			<y>-10</y>
			<z>3</z>
		</point>
		<dungeon>
			<name>Pasillo principal</name>
			<description>Un amplio corredor iluminado por extrañas antorchas que no parecen consumirse. Todavía quedan restos de telares colgando de las paredes.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>1</x>
				<y>-10</y>
				<z>2</z>
			</point>
			<point>
				<x>0</x>
				<y>-10</y>
				<z>3</z>
			</point>
		</adjacent>
	</node>
	<node>
		<point>
			<x>0</x>
			<y>-10</y>
			<z>4</z>
		</point>
		<dungeon>
			<name>Elevador</name>
			<description>Tras el gran portón aguarda una pequeña sala con lo que parece ser un antiguo elevador. Hay un hueco que recuerda a una cerradura de grna tamaño en el mecanismo del elevador. Con el objeto aecuado se puede activar.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>0</x>
				<y>-10</y>
				<z>4</z>
			</point>
		</adjacent>
	</node>
	
	<node>
		<point>
			<x>-1</x>
			<y>-11</y>
			<z>2</z>
		</point>
		<dungeon>
			<name>Catacumbas</name>
			<description>Una oscura cueva situada bajo la extraña construcción. Está bastante oscura, pero se alcanzan a ver sarcofagos apiñados contra las paredes.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>-1</x>
				<y>-11</y>
				<z>1</z>
			</point>
			<point>
				<x>-1</x>
				<y>-10</y>
				<z>2</z>
			</point>
		</adjacent>
	</node>
	<node>
		<point>
			<x>-1</x>
			<y>-11</y>
			<z>1</z>
		</point>
		<dungeon>
			<name>Profundidades de las catacumbas</name>
			<description>La cueva se extiende hasta una zona con un puente que cruza el negro vacío hasta una misteriosa puerta. El puente parece estar en muy mal estado.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>-1</x>
				<y>-11</y>
				<z>2</z>
			</point>
			<point>
				<x>0</x>
				<y>-11</y>
				<z>2</z>
			</point>
		</adjacent>
	</node>
	<node>
		<point>
			<x>0</x>
			<y>-11</y>
			<z>2</z>
		</point>
		<dungeon>
			<name>Sala secreta</name>
			<description>Extraña sala que irradia maldad. Parece haber un pequeño expositor colocado sobre una roca tallada.</description>
		</dungeon>
		<adjacent>
			<point>
				<x>-1</x>
				<y>-11</y>
				<z>1</z>
			</point>
		</adjacent>
	</node>
</map>
